### ISSUE TITLE
1385 defect prediction datasets

### ISSUE THREAD

**Issue by Suvodeep90** [ai-se/bellwether_community#14]
# todo

- [ ] if we apply these sanity checks to   GH, would we prune much?
- [ ] results with any tuning?
- [ ] sort learned by tenability. LR, linear SVM. FFT*16 (you'll have to discretize with the goal), NB (m-estiate, laplacian, how to discretize). 
        - http://robotics.stanford.edu/users/sahami/papers-dir/disc.pdf
-  [ ] start reporting how long it takes to tune
-  [ ] add in SMO: that's hard!!!!!!
- [ ] generality experiment : if u do anything, justify it!!!!
- [ ] tune for IFA reduction (just using FFT)

# expectations
The expectation from results:
1. adequacy of predictors (Pd > 66, pf < 33)
1. FSS Is useful
1. Hyperparameter optimization is useful
1. it all scales
1. stable conclusion across
1. stable conclusion locally

**Comment by Suvodeep90** [comment]
Baseline results:
Out of 1385 projects, I selected the ones with more than 50 rows in the dataset, that gave us 711 projects. Some projects had some issues. Final dataset has 633 projects. 

We applied LR(9 parameters tuned using DE). DE was tuned for F1 measure. And the chart shows f1-measure for individual projects. 

In this experiment - each project was first divided into a train(67%) and test set(33%), then the train data was further divided into train and tune set with 5 fold cross-validation. The model was trained on 80% of the data and tuned on 20%. Then the best model was tested using the test set.
![1385_baseline](https://user-images.githubusercontent.com/31140098/60670581-11300a00-9e3f-11e9-968b-3e8311c93e58.png)

**Comment by timm** [comment]
looks very nice

<em>Out of 1385 projects, I selected the ones with more than 50 rows in the dataset, that gave us 711 projects. Some projects had some issues. Final dataset has 633 projects.</em>

- that sounds like one of the repeated things that happens when u try looking at large N projects. you only find some small M that are usable

----

1. u are reporting F1. give me pf and recall as separate charts
2. u r optimizing for F1, right? why not optimize for minimizing false alarm and maximizing recall?
3. your experiment is a 3-way. can you show all 3 results? (sort the chart on the median value)
4. can your charts include the results using default LR? 
5.  you say 711 projects. there only seems 100 here, right? where are the other 600?
6. no fss? that's cool but please clarify.

**Comment by Suvodeep90** [comment]
1.  I calculated all but forgot to store the results apart from the goal in the first run.
2. I will do that.
3. I will do that 
4. I will include the results for default LR in the next result as well.
5. The chart has points for all 633 projects. Due to the size, only a few labels are getting shown.
6. The feature selector is CFS(default). I am still having issues integrating it with DE.

**Comment by Suvodeep90** [comment]
# results spreadsheet

Default LR on the dataset:
The Data was divided into Train and test set using a 5 fold cross validation with 5 repeats. There is no FSS, no Smote and use of default parameter setting for LR from sklearn.

The results are shown here are median score of 25 runs on each project. The meaures contain - 
precision,recall, f1-score, d2h, g-score, pci20, ifa.
https://docs.google.com/spreadsheets/d/1uwN4dI-kpkparZ5tj15yl7_jwwaK8lDDIU0-zc9qgyM/edit?usp=sharing

Median of Median Results:
F1:0.69
Prec:0.69
Recall:0.71
g-score:0.46
d2h:0.72
pci20:95
ifa:5

1. F1 Score:
![F1 Score 1385 dataset](https://user-images.githubusercontent.com/31140098/60734639-99391100-9f1e-11e9-85ab-c2a6833fa271.png)
2. Recall Score:
![recall vs  project](https://user-images.githubusercontent.com/31140098/60734644-9b9b6b00-9f1e-11e9-80a4-322c5023adb4.png)
3. Precision Score:
![precision vs  project](https://user-images.githubusercontent.com/31140098/60734649-9dfdc500-9f1e-11e9-85a0-0778360bcf15.png)

**Comment by Suvodeep90** [comment]
10 Random Project tuned with DE for f1-measure results - 
With FSS as CFS, Smotuned(tuned for 3 parameters), LR tuned for 10 hyper-parameters. with 5*5 cross-validation.
https://docs.google.com/spreadsheets/d/1hVMbGE4lUvWWlH5nFna5Dvyy0nLDF2nmzqHz4rOdS4Q/edit?usp=sharing

![f1, DE_f1, precision, DE_precision, recall…](https://user-images.githubusercontent.com/31140098/60738727-56cb0080-9f2d-11e9-91d6-aa6451d2c8c8.png)

Here hyper-parameter optimizer is not helping. Investigating the reason.

**Comment by Suvodeep90** [comment]
# Dataset Description(columns):
'TLOC', 'TNF', 'TNC', 'TND', 'LOC', 'CL', 'NStmt', 'NFunc',
       'RCC', 'MNL', 'avg_WMC', 'max_WMC', 'total_WMC', 'avg_DIT', 'max_DIT',
       'total_DIT', 'avg_RFC', 'max_RFC', 'total_RFC', 'avg_NOC', 'max_NOC',
       'total_NOC', 'avg_CBO', 'max_CBO', 'total_CBO', 'avg_DIT.1',
       'max_DIT.1', 'total_DIT.1', 'avg_NIV', 'max_NIV', 'total_NIV',
       'avg_NIM', 'max_NIM', 'total_NIM', 'avg_NOM', 'max_NOM', 'total_NOM',
       'avg_NPBM', 'max_NPBM', 'total_NPBM', 'avg_NPM', 'max_NPM', 'total_NPM',
       'avg_NPRM', 'max_NPRM', 'total_NPRM', 'avg_CC', 'max_CC', 'total_CC',
       'avg_FANIN', 'max_FANIN', 'total_FANIN', 'avg_FANOUT', 'max_FANOUT',
       'total_FANOUT', 'NRev', 'NFix', 'avg_AddedLOC', 'max_AddedLOC',
       'total_AddedLOC', 'avg_DeletedLOC', 'max_DeletedLOC',
       'total_DeletedLOC', 'avg_ModifiedLOC', 'max_ModifiedLOC',
       'total_ModifiedLOC','Buggy'

**Comment by timm** [comment]
# Thirteen questions

i feel like we are closing in on a methodology, a check list of sorts for large scale data mining. e.g. if we started building a library of sanity check demons as per for first point then we'd have a product to offer other people

please, for the 1385 can you clarify the following:

1. what sanity checks on the data? 
      - In the original paper out of 235K projects 1385 projects were selected based on:
              - Filtering Out Projects by Programming Languages(only object-oriented i.e *.c, *.cpp, *.cxx, *.cc, *.cs, *.java, and *.pas).
              - Filtering Out the Projects with a Small Number of Commit(filter out the projects with less than 32 which is less then 25% quantile of the number of commits on all projects).
              - Filtering Out the Projects with Lifespan Less Than One Year.
              - Filtering Out the Projects with Limited Defect Data(i.e. count the number of fix-inducing and non-fixing commits from a one-year period. We choose the 75 % quantile of the number of fix-inducing (respectively non-fixing) commits as the threshold to filter out the projects with fewer defect data).
              - Filtering Out the Projects Without Fix-Inducing Commits.
      - I selected the ones with more than 50 rows in the dataset
      - Some projects had some issues (i.e. projects don't have enough buggy to non-buggy ratio to create a stratified k=5 fold cross-validation).
          - reduced   711 projects to  633 projects  (if in cross val there were zero defect buckets
            in train or test, removed those results).  
      - you need more. please code up the checks in
       https://bura.brunel.ac.uk/bitstream/2438/7926/2/TSE_NASADataQualNote_V26.pdf, plus any else you can think of
       - We do need to apply our GitHub 6 point check.(not done yet)
1. how much data culled by the sanity checks?
       - original paper's sanity check culled 99% of projects.
       - New sanity check culled 54% of the remaining.
1. what attributes
      - Listed above. All product measures I think, no process or personnel. (Most are product metrics collected using understand tool then converted to the following attributes, there are few process metrics like "Number of revisions","Number of revisions a file was involved in bug-fixing" etc. , . There are raw data collected using understand and then there are converted metrics which I am using now as did the authors).
        - process metrics: Number of revisions, Number of revisions a file was involved in bug-fixing, Lines added, Lines deleted, Lines modified.
1. how many rows?
      - Final dataset has 633 projects.
1. what does each row represent?
      - each row is a class/file 
1. how is class labelling done?
     - 58% of projects had issues tracking system, bug reports were collected from there and labeled using that.
     - 42% projects didn't have a tracking system, they were labeled using the keyword search in the commit message (i.e. bug|fix|error|issue|crash|problem|fail|defect|patch).
1. what FSS
     - CFS is being used for feature selection. Except for default results which doesn't use any FSS.
1. what learner
      - LR
      - why only LR? (I will be using other learners as well. LR was fast to train, I tried with SVM it was slow but i have coded up to use other learners as well)
1. what pre-processing
      - none?
      - SMOTEUNED is being used for class imbalance.
      - Planning to use SMOTE for default models without Hyper-parametre optimization. 
1. what hyperparaemeter optimization on the pre-precessor?
      - none?
      - DE
1. what hyperparaemeter optimization on the learner?
      - differential evolution on LR
      - optimizing for F1
      - which means that PF can get sometimes very high,
      - can we run the optimizer again, this time for max pd, min pf? (Used pd for optimization i have few results but not formatted yet)
      - Q: do u know how to do multi-objective optimization with DE? A: use the cdom score... do u know how to do that? (I have never done that before, but i will code it up)
1. what success criteria?
      - pf, ifa, d2h
      - recall, pd (you've got both, why are they different numbers?
      - pci_20. is that the same as my popt20? where the
          learners dived modules into guess=defective|ok then sort defective on LOC, the sort ok on LOC, then run over that sort, defective before or?
1. what is the train/test rig?
      - train 66,  and test set(33%), 
      - 5 way cross val on train, best model see after testing
         on 20% of 66% based on to test

there are some wondrous things about the results:

- crazy high pci_20. bug in scripts? (yes I think I made a mistake)
- really good IFAs.
      - how do these compare with the IFAs reported by David Lo at ICSME'17? are they better than? (their median was 4.1 out default(without DE) median is 5)
- low median PFs (good) somethings very high 
      -   can we optimize for lower pf? 
- mediocre  PDs but i think the iFS make up for that

**Comment by timm** [comment]
there's something wrong with your options.

lami and ambidata has the expected effect (DE improves things). the other datasets do not see that improve 

![image](https://user-images.githubusercontent.com/29195/60749767-d1674080-9f6c-11e9-9bbc-f6737b014134.png)

but the other data sets show no improvement.

so:

- Q1 is training for F1 bad?
- Q2: these numbers are better than what you found before, right? so to what do you attribute the performance improvement? SMOTE?: 

This new results are from the new dataset, i think the data quality is better than the commit guru dataset. The same rig is being applied to the both dataset.

**Comment by Suvodeep90** [comment]
I am not exactly sure why this is happening. But i am rechecking if there is some issue or not. In the mean time i will train for pd. I have not tried to optimize DE with dom score before, but i know the concept, i am trying to code that up. 

Also I will update the answers to the last comment shortly.

**Comment by timm** [comment]
# amazingly good 

if it essentially the same rig as used for CommitGuru150 then the source of this quick might be in the data, not your algorithms. the performance here is **amazingly** good. did u read the paper this data came from? (*) all the careful human curation? this data set could be somewhat exceptional

(*) BTW, applying the rule of **KNOW THY DATA**, that is a requirement, not. a question. 

The original dataset was collected by Dr. Mockus from SourceForge and GoogleCode. 


----------
suvodeep comments that this data was severely pruned prior to analysus

the results here seen high w.r.t other results we have seen in other data sets. this could either be a selection bias here (but the sanity checks seem sane) or it could be the result of poor pre-processing in other data sets.

- how to assess if these sanity rules are sane?
- if we apply them to the top started items in GH, would we prune much? ❓

**Comment by timm** [comment]
could you edit https://github.com/ai-se/bellwether_community/issues/14#issuecomment-508883462 and make sure all the 13 points are addressed?

**Comment by timm** [comment]
# Lessons Learned #

## need to assess learners via their tune ability

And LR is fast! and polynomial SVM is slow

## when you look at lots of data, you discard most of it. e.g

- mocks 235,000 ==> 1385 = 0.59%
- e.g. GitHub. in a sample of 50000, our sail checks select 1011; i.e.  2.02%

**Comment by timm** [comment]
# pars inside NB

```lua
local Lib    = require("lib")
local Burn   = require("burn")
local Learn  = require("learn")
local Object = require("object")

Nb = {}
Nb = Object:new{maybes=0, name="nb"}

--------- --------- --------- --------- --------- --------- 
function Nb:new()
  local n=Object.new(self)
  n.datas={}
  return n
end

function Nb:like(cells, data1, m,k, n,     inc)
  local prior= ( #data1.rows + k ) / ( n+ k*self.maybes )
  local like = math.log(prior)
  for _,col in pairs(data1.x.cols) do 
    local x = cells[ col.pos ]
    if x ~= Burn.ignore then
      if col:nump() then
        inc = Lib.normal(x, col.mu, col:sd())
      else
        inc = ( (col.counts or 0) + m * prior ) /
              ( #data1.rows + m )
      end
      like = like + math.log(inc) end end 
  return like
end

function Nb:what(cells,data0)
  local c = cells[ data0._class.pos ]
  if not self.datas[c] then 
    self.maybes = self.maybes + 1
    self.datas[c] = data0:clone()
  end
  return self.datas[c]
end

function Nb:inc(cells,data0)
  local data1 = self:what(cells,data0)
  data1:inc(cells)
  data0:inc(cells)
end

function Nb:predict(cells,data0)
  local max,got = -10^32,nil
  for h1,data1 in pairs(self.datas) do
    got = got or h1
    local l = self:like(cells, data1, Burn.nb.m, 
                        Burn.nb.k, #data0.rows)
    if l > max then  max,got = l,h1 end 
  end
  return got
end

function Nb:report(era,goal,log)
  Learn.report(era,log,self.name,goal)
end

return Nb
```

**Comment by timm** [comment]
# generality experiment

- group of increasing size, 10,20,40,80,160.31,640,1320
- group by your clusterer
- group at random

## feature extractor: is the same model?

- CART: frequency counts
- LR: variance on the \beta

http://menzies.us/pdf/12localb.pdf

![image](https://user-images.githubusercontent.com/29195/60827816-0cd95900-a17f-11e9-9bc3-b45134700bc2.png)

![image](https://user-images.githubusercontent.com/29195/60827840-1367d080-a17f-11e9-93bd-85c0618eac43.png)

**Comment by timm** [comment]
# Tuning heuristics

- don't tune all, tune in batches https://fada.birzeit.edu/bitstream/20.500.11889/4529/1/176ef4196797603ae2ca68ff353bb4233668.pdf
- goto to SMBO or DODGE

**Comment by timm** [comment]
# Generation heuristics

- if highly constrained use a sat solver

![image](https://user-images.githubusercontent.com/29195/60829457-eddcc600-a182-11e9-9a80-3d2ce44c06c8.png)

**Comment by Suvodeep90** [comment]
![buggyness_hist](https://user-images.githubusercontent.com/31140098/60842466-2f309e00-a1a2-11e9-8d1f-e523e6c4ed93.png)
![buggyness](https://user-images.githubusercontent.com/31140098/60842467-2f309e00-a1a2-11e9-8ec7-929f44c462b4.png)
![pf](https://user-images.githubusercontent.com/31140098/60842468-2f309e00-a1a2-11e9-92a8-f3516485b70b.png)
![pd](https://user-images.githubusercontent.com/31140098/60842469-2f309e00-a1a2-11e9-8f73-7a9e280de2a7.png)
![log-ifa](https://user-images.githubusercontent.com/31140098/60842470-2fc93480-a1a2-11e9-9e39-602474033754.png)
![popt20](https://user-images.githubusercontent.com/31140098/60842471-2fc93480-a1a2-11e9-8152-96468262d08b.png)
![d2h](https://user-images.githubusercontent.com/31140098/60842472-2fc93480-a1a2-11e9-8d25-1fff673f6cd3.png)
![g-score](https://user-images.githubusercontent.com/31140098/60842474-2fc93480-a1a2-11e9-8a89-75224acb259d.png)
![Precision](https://user-images.githubusercontent.com/31140098/60842475-2fc93480-a1a2-11e9-804f-38f08fcdeaf7.png)
![F1 - Score](https://user-images.githubusercontent.com/31140098/60842477-2fc93480-a1a2-11e9-92c4-d49075c8f29a.png)

**Comment by timm** [comment]
hey... what's the above new charts?

these are the new charts with updated metric calculations .. I just wanted to store them somewhere. not ready for reporting yet..

**Comment by Suvodeep90** [comment]
Use of BIRCH algorithm in SE:
https://scholar.google.com/scholar?hl=en&as_sdt=5%2C34&sciodt=0%2C34&cites=16182634092879736016&scipsc=1&q=source%3AIEEE+Transaction+on+Software+Engineering&btnG=

**Comment by Suvodeep90** [comment]
Time:

160 projects: - 73053 secs

**Comment by timm** [comment]
- fix potp20
-fft smotuned, fss
    - feel free to run smotuned and fss just once per data set
    - feel free NOT to computing bellwether for largest N
- eval criiteria
- report everything desperately (pd, pf, ifa)
- consider what ur moving from n/2 to n
    - just the name of the bellwether data
    - model learned from the bellwether
- cool idea: see if the bellwether works on the really small data sets

**Comment by Suvodeep90** [comment]
Hierarchical Clustering results:

[cluster_id=0] N_children: 9 N_samples: 697
> [cluster_id=1] N_children: 9 N_samples: 87

- > > [cluster_id=2] N_children: 0 N_samples: 2
- > > [cluster_id=3] N_children: 0 N_samples: 7
- > > [cluster_id=4] N_children: 0 N_samples: 17
- > > [cluster_id=5] N_children: 0 N_samples: 6
- > > [cluster_id=6] N_children: 0 N_samples: 18
- > > [cluster_id=7] N_children: 0 N_samples: 15
- > > [cluster_id=8] N_children: 0 N_samples: 12
- > > [cluster_id=9] N_children: 0 N_samples: 6
- > > [cluster_id=10] N_children: 0 N_samples: 4

> [cluster_id=11] N_children: 2 N_samples: 4

- > > [cluster_id=12] N_children: 0 N_samples: 1
- > > [cluster_id=13] N_children: 0 N_samples: 3

> [cluster_id=14] N_children: 10 N_samples: 103

- > > [cluster_id=15] N_children: 0 N_samples: 3
- > > [cluster_id=16] N_children: 0 N_samples: 4
- > > [cluster_id=17] N_children: 0 N_samples: 16
- > > [cluster_id=18] N_children: 0 N_samples: 11
- > > [cluster_id=19] N_children: 0 N_samples: 19
- > > [cluster_id=20] N_children: 0 N_samples: 3
- > > [cluster_id=21] N_children: 0 N_samples: 10
- > > [cluster_id=22] N_children: 0 N_samples: 6
- > > [cluster_id=23] N_children: 0 N_samples: 13
- > > [cluster_id=24] N_children: 0 N_samples: 18

> [cluster_id=25] N_children: 0 N_samples: 2
> [cluster_id=26] N_children: 0 N_samples: 4
> [cluster_id=27] N_children: 0 N_samples: 1
> [cluster_id=28] N_children: 6 N_samples: 64

- > > [cluster_id=29] N_children: 0 N_samples: 9
- > > [cluster_id=30] N_children: 0 N_samples: 12
- > > [cluster_id=31] N_children: 0 N_samples: 15
- > > [cluster_id=32] N_children: 0 N_samples: 16
- > > [cluster_id=33] N_children: 0 N_samples: 5
- > > [cluster_id=34] N_children: 0 N_samples: 7

> [cluster_id=35] N_children: 19 N_samples: 222

- > > [cluster_id=36] N_children: 0 N_samples: 12
- > > [cluster_id=37] N_children: 0 N_samples: 10
- > > [cluster_id=38] N_children: 0 N_samples: 4
- > > [cluster_id=39] N_children: 0 N_samples: 19
- > > [cluster_id=40] N_children: 0 N_samples: 20
- > > [cluster_id=41] N_children: 0 N_samples: 11
- > > [cluster_id=42] N_children: 0 N_samples: 16
- > > [cluster_id=43] N_children: 0 N_samples: 8
- > > [cluster_id=44] N_children: 0 N_samples: 13
- > > [cluster_id=45] N_children: 0 N_samples: 7
- > > [cluster_id=46] N_children: 0 N_samples: 17
- > > [cluster_id=47] N_children: 0 N_samples: 19
- > > [cluster_id=48] N_children: 0 N_samples: 6
- > > [cluster_id=49] N_children: 0 N_samples: 5
- > > [cluster_id=50] N_children: 0 N_samples: 12
- > > [cluster_id=51] N_children: 0 N_samples: 13
- > > [cluster_id=52] N_children: 0 N_samples: 19
- > > [cluster_id=53] N_children: 0 N_samples: 4
- > > [cluster_id=54] N_children: 0 N_samples: 7

> [cluster_id=55] N_children: 20 N_samples: 210

- > > [cluster_id=56] N_children: 0 N_samples: 11
- > > [cluster_id=57] N_children: 0 N_samples: 18
- > > [cluster_id=58] N_children: 0 N_samples: 3
- > > [cluster_id=59] N_children: 0 N_samples: 13
- > > [cluster_id=60] N_children: 0 N_samples: 9
- > > [cluster_id=61] N_children: 0 N_samples: 18
- > > [cluster_id=62] N_children: 0 N_samples: 15
- > > [cluster_id=63] N_children: 0 N_samples: 2
- > > [cluster_id=64] N_children: 0 N_samples: 5
- > > [cluster_id=65] N_children: 0 N_samples: 13
- > > [cluster_id=66] N_children: 0 N_samples: 6
- > > [cluster_id=67] N_children: 0 N_samples: 11
- > > [cluster_id=68] N_children: 0 N_samples: 2
- > > [cluster_id=69] N_children: 0 N_samples: 1
- > > [cluster_id=70] N_children: 0 N_samples: 11
- > > [cluster_id=71] N_children: 0 N_samples: 18
- > > [cluster_id=72] N_children: 0 N_samples: 18
- > > [cluster_id=73] N_children: 0 N_samples: 20
- > > [cluster_id=74] N_children: 0 N_samples: 7
- > > [cluster_id=75] N_children: 0 N_samples: 9

**Comment by timm** [comment]
1. rejig report 
     - n>.66
     - n < 0.33
2. add stats test against the original and each other. color in back the winner and anyone sillier to the winner
3. think about: Not using old data (the self test problem)
4. Scale up bellwether 
   - don't do N^2 do 20*N
    - don't do similar projects. Collect column stats, and 
         -   Sort by difference, take  the 20 projects most distance to you
    - cluster once with birch: build bellwether from most central project in each leaf
5. Better learns
    - Fftrees: I predict u won't need fss and precision will be better if you discretize for precision

**Comment by Suvodeep90** [comment]
Ideas:

To apply hyper-parameter optimization .. if we tune each project separately and apply and select the best model out of them to use it as bellwether.

**Comment by Suvodeep90** [comment]
Stats Test (compare with self test)

F1 score 
![image](https://user-images.githubusercontent.com/31140098/61644859-81c68b80-ac73-11e9-8eff-ad54c55b9833.png)

Precision
![image](https://user-images.githubusercontent.com/31140098/61644903-986ce280-ac73-11e9-8ebe-f4079ce71c67.png)

Recall
![image](https://user-images.githubusercontent.com/31140098/61644947-ac184900-ac73-11e9-9640-d137d5f607a5.png)

g-score
![image](https://user-images.githubusercontent.com/31140098/61644979-b63a4780-ac73-11e9-9e84-175a7f9c5ccd.png)

pf
![image](https://user-images.githubusercontent.com/31140098/61645006-c0f4dc80-ac73-11e9-82a7-33543dd4376b.png)

**Comment by Suvodeep90** [comment]
in each community(cluster) can we find bellwether using stats test, and the models who rank best are the bellwether?

**Comment by timm** [comment]
we can if we want to be slow. but lets see what happens if we bellwether on steroids first

**Comment by timm** [comment]
any news on 600+?
